print("   Python is a high level interpreted programming language.")
print("=> Easy to write.")
print("=> Used in AI, ML, Web Development, DS, Automation, etc.")
print("          ")
print("     Features   ")
print("    ---------- ")
print("         ")
print("* Simple Syntex")
print("* Free and open source")
print("* Plateform independent")
print("* Large library support", "and many more")